---
- name: copy war file to tomcat
  maven_artifact:
    group_id: com.maha
    artifact_id: savina-login
    repository_url: 'http://3.128.189.3:8081/repository/savina-login/com/maha/savina-login/1.0/savina-login-1.0.war'
    username: admin
    password: admin123
    dest: /opt/tomcat/webapps/savina-login-1.0.war

    