---
- name: deploy java application
  get_url:
    url: http://3.128.189.3:8081/repository/savina-login/com/maha/savina-login/{{my}}/savina-login-{{my}}.war
    dest: /opt/tomcat/webapps/savina-login.war
    username: admin
    password: admin123
    force_basic_auth: yes
  notify: restart tomcat 